const C={
"Falazás":{t:["falazókanál","vízmérték","mérőszalag","falazózsinór","gumikalapács","vödör","talicska","lapát"],m:["falazóelem / tégla","falazóhabarcs vagy falazóragasztó","víz"]},
"Vakolás":{t:["vakolókanál","simító","glettvas","vízmérték","mérőszalag","keverőgép","vödör","talicska"],m:["vakolóhabarcs","víz","alapozó / tapadóhíd","élvédő, ha szükséges"]},
"Betonozás":{t:["keverőgép","lapát","talicska","vödör","lehúzóléc","simító","vízmérték"],m:["cement","homok / sóder","kavics, ha szükséges","víz","betonacél, ha szükséges"]},
"Zsaluzás":{t:["kalapács","mérőszalag","vízmérték","fűrész","csavarozó","fogó","jelölőceruza"],m:["zsaludeszka / zsalutábla","csavarok / szegek","faanyag","távtartók"]},
"Bontás":{t:["bontókalapács","vésőgép","kalapács","véső","feszítővas","flex","lapát","talicska","ipari porszívó"],m:["sittes zsák","védőfólia","konténer, ha szükséges"]},
"Szigetelés":{t:["sniccer","mérőszalag","vízmérték","lézer","fogazott glettvas","simító","fúrógép","csavarozó","dübelbeütő","vödör","keverőgép","létra / állvány"],m:["szigetelőanyag","ragasztó","dübel","üvegszövet háló","élvédő","alapozó","profilok"]},
"Hőszigetelés":{t:["sniccer","mérőszalag","vízmérték","lézer","fogazott glettvas","simító","fúrógép","dübelbeütő","keverőgép","vödör"],m:["hőszigetelő lap","ragasztó","dübel","üvegszövet háló","élvédő","alapozó","színezővakolat"]},
"Vízszigetelés":{t:["simító","fogazott glettvas","henger","ecset","snitzer","vödör","keverőgép","mérőszalag"],m:["vízszigetelő anyag","kent szigetelés","szigetelőszalag","hajlaterősítő szalag","alapozó"]},
"Burkolás":{t:["csempevágó","flex","gyémánttárcsa","fogazott glettvas","gumikalapács","vízmérték","lézer","fugakereszt","fugázó gumi","vödör","keverőgép","szintező rendszer"],m:["burkolólap","csemperagasztó","fuga","alapozó","szilikon","szintező ék / klipsz"]},
"Padloponozás / aljzatkiegyenlítés":{t:["keverőgép","vödör","mérőedény","tüskés henger","lehúzó","simító","spakli","vízmérték / lézer"],m:["aljzatkiegyenlítő","alapozó","víz","szegélyszalag"]},
"Glettelés":{t:["glettvas","spakli","csiszolórács / csiszoló","csiszológép","keverőgép","vödör","munkalámpa"],m:["glettanyag","mélyalapozó","csiszolóanyag","hézagerősítő szalag, ha szükséges"]},
"Festés":{t:["festőhenger","ecset","festéktálca","teleszkópos nyél","spakli","csiszoló","takarófólia","maszkolószalag","létra"],m:["festék","mélyalapozó","glettanyag","takarófólia","maszkolószalag"]},
"Színezés":{t:["simító","rozsdamentes glettvas","keverőgép","vödör","henger","ecset","állvány / létra"],m:["színezővakolat","alapozó","üvegszövet háló","élvédő","profilok"]},
"Profilozás":{t:["mérőszalag","vízmérték","lézer","csavarozó","fúrógép","fémolló","snitzer","fogó","jelölőceruza"],m:["UD / CD profil","UW / CW profil","sarokprofil","élvédő profil","dübelek","csavarok"]},
"Gipszkartonozás":{t:["csavarozó","lézer vagy vízmérték","mérőszalag","gipszkartonvágó","snitzer","olló lemezhez","spakli"],m:["gipszkarton lap","UD / CD profil","csavarok","dübelek","hézagerősítő szalag","glettanyag"]},
"Állványozás":{t:["kalapács","vízmérték","mérőszalag","csavarkulcs","feszítővas","létra","védőfelszerelés"],m:["állványelemek","járólapok / deszkák","rögzítő elemek","korlát / lábdeszka"]},
"Térkövezés":{t:["lapát","talicska","seprű","gumikalapács","vízmérték vagy lézer","vágógép","lapvibrátor"],m:["térkő","ágyazóanyag","homok","szegélykő","beton, ha szükséges"]},
"Aljzatbetonozás":{t:["keverőgép","lapát","talicska","lehúzóléc","vízmérték vagy lézer","simító","vödör"],m:["cement","homok / sóder","víz","dilatációs szalag","fólia, ha szükséges"]},
"Betoncsiszolás":{t:["betoncsiszoló","ipari porszívó","hosszabbító","sarokcsiszoló","védőszemüveg","porálarc"],m:["csiszolókorong / gyémántszerszám","javítóanyag, ha szükséges"]},
"Fúrás / vésés":{t:["fúrókalapács","vésőgép","fúrógép","fúrószárak","vésők","ipari porszívó","hosszabbító"],m:["dübelek","csavarok","javítóanyag"]},
"Nyílászáró körüli javítás":{t:["kalapács","véső","snitzer","mérőszalag","vízmérték","fúrógép","csavarozó","spakli","habpisztoly"],m:["purhab","javítóhabarcs","glettanyag","dübel","csavar","szigetelőszalag"]},
"Kőműves javítások":{t:["kalapács","véső","falazókanál","spakli","simító","vízmérték","mérőszalag","keverőgép","vödör"],m:["javítóhabarcs","cement","homok","falazóanyag","glettanyag","víz"]},
"Tereprendezés":{t:["lapát","ásó","gereblye","talicska","döngölő","mérőszalag","lézer / szintező"],m:["töltőanyag","homok","sóder","termőföld","szegélykő, ha szükséges"]},
"Anyagmozgatás":{t:["talicska","molnárkocsi","heveder","gurulós kocsi","lapát","vödör"],m:[]},
"Takarítás / munkaterület-rendezés":{t:["seprű","lapát","ipari porszívó","vödör","felmosó","kézikocsi"],m:["szemeteszsák","tisztítószer","védőfólia"]}
};
const KEY="nka_v2_fixed";let s=JSON.parse(localStorage.getItem(KEY)||"null")||{works:[],tools:{},materials:{},ownT:[],ownM:[]},mode="";const $=q=>document.querySelector(q),esc=x=>String(x).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
function save(){localStorage.setItem(KEY,JSON.stringify(s));render()}function list(k){const a=new Set();s.works.forEach(w=>(C[w]?.[k]||[]).forEach(x=>a.add(x)));(k==="t"?s.ownT:s.ownM).forEach(x=>a.add(x));return[...a]}
function drawWorks(){$("#works").innerHTML=Object.keys(C).map(w=>`<button class="${s.works.includes(w)?"active":""}" data-w="${esc(w)}">${esc(w)}</button>`).join("");document.querySelectorAll("[data-w]").forEach(b=>b.onclick=()=>{const w=b.dataset.w;s.works=s.works.includes(w)?s.works.filter(x=>x!==w):[...s.works,w];save()})}
function drawSelected(){$("#selected").innerHTML=s.works.map(w=>`<span class="tag">${esc(w)}<button type="button" data-r="${esc(w)}">×</button></span>`).join("");document.querySelectorAll("[data-r]").forEach(b=>b.onclick=()=>{s.works=s.works.filter(x=>x!==b.dataset.r);save()})}
function draw(k){const isT=k==="t",arr=list(k),el=$(isT?"#tools":"#materials"),checked=isT?s.tools:s.materials,own=isT?s.ownT:s.ownM;if(!arr.length){el.innerHTML='<div class="empty">Először válassz legalább egy munkafolyamatot.</div>';return}el.innerHTML=arr.map(n=>`<label class="item"><input type="checkbox" ${checked[n]?"checked":""} data-k="${k}" data-n="${esc(n)}"><span class="itemmain"><span class="name">${esc(n)}</span><span class="source">${own.includes(n)?"Saját tétel":"Szakmai alapjavaslat"}</span></span>${own.includes(n)?'<em class="own">SAJÁT</em>':""}</label>`).join("");el.querySelectorAll("input").forEach(i=>i.onchange=()=>{(i.dataset.k==="t"?s.tools:s.materials)[i.dataset.n]=i.checked;save()})}
function render(){drawWorks();drawSelected();draw("t");draw("m");const t=list("t"),m=list("m"),total=t.length+m.length,checked=t.filter(x=>s.tools[x]).length+m.filter(x=>s.materials[x]).length;$("#workCount").textContent=s.works.length;$("#checked").textContent=checked;$("#total").textContent=total;$("#bar").style.width=total?Math.round(checked/total*100)+"%":"0%"}
$("#addWork").onclick=()=>{const i=$("#newWork"),n=i.value.trim();if(!n)return;if(!C[n])C[n]={t:[],m:[]};if(!s.works.includes(n))s.works.push(n);i.value="";save()};$("#newWork").onkeydown=e=>{if(e.key==="Enter")$("#addWork").click()};
function openDlg(k){mode=k;$("#dlgTitle").textContent=k==="t"?"Saját szerszám":"Saját anyag";$("#dlgText").textContent=k==="t"?"Adj hozzá egy olyan szerszámot, ami neked kell.":"Adj hozzá egy olyan anyagot, ami neked kell.";$("#dlgInput").value="";$("#dlg").showModal();$("#dlgInput").focus()}$("#addTool").onclick=()=>openDlg("t");$("#addMaterial").onclick=()=>openDlg("m");$("#cancel").onclick=()=>$("#dlg").close();$("#form").onsubmit=e=>{e.preventDefault();const n=$("#dlgInput").value.trim();if(!n)return;const a=mode==="t"?s.ownT:s.ownM;a.includes(n)||a.push(n);(mode==="t"?s.tools:s.materials)[n]=true;$("#dlg").close();save()};$("#reset").onclick=()=>{if(confirm("Biztosan törlöd a mai munkanapot?")){s={works:[],tools:{},materials:{},ownT:[],ownM:[]};save()}};render();
