const catalog={"Falazás":{t:["falazókanál","vízmérték","mérőszalag","falazózsinór","gumikalapács","vödör","talicska","lapát"],m:["falazóelem / tégla","falazóhabarcs vagy falazóragasztó","víz"]},"Vakolás":{t:["vakolókanál","simító","glettvas","vízmérték","mérőszalag","keverőgép","vödör","talicska"],m:["vakolóhabarcs","víz","alapozó / tapadóhíd","élvédő, ha szükséges"]},"Betonozás":{t:["keverőgép","lapát","talicska","vödör","lehúzóléc","simító","vízmérték"],m:["cement","homok / sóder","kavics, ha szükséges","víz","betonacél, ha szükséges"]},"Zsaluzás":{t:["kalapács","mérőszalag","vízmérték","fűrész","csavarozó","fogó","jelölőceruza"],m:["zsaludeszka / zsalutábla","csavarok / szegek","faanyag","távtartók"]},"Gipszkartonozás":{t:["csavarozó","lézer vagy vízmérték","mérőszalag","gipszkartonvágó","snitzer","olló lemezhez","spakli"],m:["gipszkarton lap","UD / CD profil","csavarok","dübelek","hézagerősítő szalag","glettanyag"]},"Aljzatbeton készítés":{t:["keverőgép","lapát","talicska","lehúzóléc","vízmérték vagy lézer","simító","vödör"],m:["cement","homok / sóder","víz","dilatációs szalag","fólia, ha szükséges"]},"Térkövezés":{t:["lapát","talicska","gumilapát / seprű","gumikalapács","vízmérték vagy lézer","vágógép","lapvibrátor"],m:["térkő","ágyazóanyag","homok","szegélykő","beton, ha szükséges"]}};
const K="nka_v1";let s=JSON.parse(localStorage.getItem(K)||"null")||{w:[],d:{},ct:[],cm:[]},mode="";const $=x=>document.querySelector(x),esc=x=>x.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
function save(){localStorage.setItem(K,JSON.stringify(s));render()}function all(type){let a=new Set();s.w.forEach(w=>(catalog[w]?.[type]||[]).forEach(x=>a.add(x)));(type==='t'?s.ct:s.cm).forEach(x=>a.add(x));return[...a]}function ck(type,n){return s.d[type+':'+n]>0}function toggle(type,n,v){s.d[type+':'+n]=(s.d[type+':'+n]||0)+(v?1:-1);save()}
function render(){
$('#works').innerHTML=Object.keys(catalog).map(w=>`<button class="${s.w.includes(w)?'active':''}" data-w="${esc(w)}">${esc(w)}</button>`).join('');document.querySelectorAll('[data-w]').forEach(b=>b.onclick=()=>{let w=b.dataset.w;s.w=s.w.includes(w)?s.w.filter(x=>x!==w):[...s.w,w];save()});
$('#selected').className='selected';$('#selected').innerHTML=s.w.map(w=>`<span class="tag">${esc(w)} <button class="x" data-x="${esc(w)}">×</button></span>`).join('');document.querySelectorAll('[data-x]').forEach(b=>b.onclick=()=>{s.w=s.w.filter(w=>w!==b.dataset.x);save()});
list('t',$('#tools'));list('m',$('#mats'));$('#wc').textContent=s.w.length;let t=all('t'),m=all('m'),total=t.length+m.length,c=t.filter(x=>ck('t',x)).length+m.filter(x=>ck('m',x)).length;$('#tc').textContent=t.length;$('#mc').textContent=m.length;$('#cc').textContent=c;$('#bar').style.width=(total?c/total*100:0)+'%';$('#dc').textContent=Object.values(s.d).filter(x=>x).length}
function list(type,el){let a=all(type);if(!a.length){el.className='list empty';el.textContent='Először válassz munkafolyamatot.';return}el.className='list';el.innerHTML=a.map(n=>{let custom=(type==='t'?s.ct:s.cm).includes(n);return `<label class="item"><input type="checkbox" ${ck(type,n)?'checked':''}><span><b>${esc(n)}</b><small>${custom?'Saját tétel':'Szakmai javaslat'}</small></span>${custom?'<span class="custom">SAJÁT</span>':''}</label>`}).join('');el.querySelectorAll('input').forEach((i,j)=>i.onchange=()=>toggle(type,a[j],i.checked))}
$('#addWork').onclick=()=>{let n=$('#newWork').value.trim();if(!n)return;if(!catalog[n])catalog[n]={t:[],m:[]};if(!s.w.includes(n))s.w.push(n);$('#newWork').value='';save()};$('#newWork').onkeydown=e=>{if(e.key==='Enter')$('#addWork').click()};
function open(type){mode=type;$('#dt').textContent=type==='t'?'Saját szerszám':'Saját anyag';$('#dp').textContent=type==='t'?'Adj hozzá egy saját szerszámot.':'Adj hozzá egy saját anyagot.';$('#di').value='';$('#dlg').showModal();$('#di').focus()}$('#addTool').onclick=()=>open('t');$('#addMat').onclick=()=>open('m');$('#cancel').onclick=()=>$('#dlg').close();$('#form').onsubmit=e=>{e.preventDefault();let n=$('#di').value.trim(),a=mode==='t'?s.ct:s.cm;if(n&&!a.includes(n))a.push(n);if(n)s.d[mode+':'+n]=1;$('#dlg').close();save()};$('#reset').onclick=()=>{if(confirm('Biztosan törlöd a mai munkanapot és a helyi döntéseket?')){s={w:[],d:{},ct:[],cm:[]};save()}};render();
