const C={
"Falazás":{t:["falazókanál","vízmérték","lézer / szintező","mérőszalag","falazózsinór","gumikalapács","vödör","talicska","lapát","hosszú alumínium léc"],m:["falazóelem / tégla","falazóhabarcs vagy falazóragasztó","víz"]},
"Vakolás":{t:["vakolókanál","simító","glettvas","vízmérték","mérőszalag","keverőgép","vödör","talicska","hosszú alumínium léc"],m:["vakolóhabarcs","víz","alapozó / tapadóhíd","élvédő, ha szükséges"]},
"Betonozás":{t:["keverőgép","lapát","talicska","vödör","lehúzóléc","simító","vízmérték","lézer / szintező"],m:["cement","homok / sóder","kavics, ha szükséges","víz","betonacél, ha szükséges"]},
"Zsaluzás":{t:["kalapács","mérőszalag","vízmérték","fűrész","csavarozó","fogó","jelölőceruza"],m:["zsaludeszka / zsalutábla","csavarok / szegek","faanyag","távtartók"]},
"Bontás":{t:["bontókalapács","vésőgép","kalapács","véső","feszítővas","flex","lapát","talicska","ipari porszívó"],m:["sittes zsák","védőfólia","konténer, ha szükséges"]},
"Szigetelés":{t:["sniccer","mérőszalag","vízmérték","lézer / szintező","fogazott glettvas","simító","fúrógép","csavarozó","dübelbeütő","vödör","keverőgép","létra / állvány"],m:["szigetelőanyag","ragasztó","dübel","üvegszövet háló","élvédő","alapozó","profilok"]},
"Hőszigetelés":{t:["sniccer","mérőszalag","vízmérték","lézer / szintező","fogazott glettvas","simító","fúrógép","dübelbeütő","keverőgép","vödör","létra / állvány"],m:["hőszigetelő lap","ragasztó","dübel","üvegszövet háló","élvédő","alapozó","színezővakolat"]},
"Vízszigetelés":{t:["simító","fogazott glettvas","henger","ecset","sniccer","vödör","keverőgép","mérőszalag"],m:["vízszigetelő anyag","kent szigetelés","szigetelőszalag","hajlaterősítő szalag","alapozó"]},
"Burkolás":{t:["csempevágó","flex","gyémánttárcsa","fogazott glettvas","gumikalapács","vízmérték","lézer / szintező","fugakereszt","fugázó gumi","vödör","keverőgép","szintező rendszer"],m:["burkolólap","csemperagasztó","fuga","alapozó","szilikon","szintező ék / klipsz"]},
"Padloponozás / aljzatkiegyenlítés":{t:["keverőgép","vödör","mérőedény","tüskés henger","lehúzó","simító","spakli","vízmérték / lézer"],m:["aljzatkiegyenlítő","alapozó","víz","szegélyszalag"]},
"Glettelés":{t:["glettvas","spakli","csiszolórács / csiszoló","csiszológép","keverőgép","vödör","munkalámpa"],m:["glettanyag","mélyalapozó","csiszolóanyag","hézagerősítő szalag, ha szükséges"]},
"Festés":{t:["festőhenger","ecset","festéktálca","teleszkópos nyél","spakli","csiszoló","takarófólia","maszkolószalag","létra"],m:["festék","mélyalapozó","glettanyag","takarófólia","maszkolószalag"]},
"Színezés":{t:["simító","rozsdamentes glettvas","keverőgép","vödör","henger","ecset","állvány / létra"],m:["színezővakolat","alapozó","üvegszövet háló","élvédő","profilok"]},
"Profilozás":{t:["mérőszalag","vízmérték","lézer / szintező","csavarozó","fúrógép","fémolló","sniccer","fogó","jelölőceruza"],m:["UD / CD profil","UW / CW profil","sarokprofil","élvédő profil","dübelek","csavarok"]},
"Gipszkartonozás":{t:["csavarozó","lézer vagy vízmérték","mérőszalag","gipszkartonvágó","sniccer","lemezolló","spakli"],m:["gipszkarton lap","UD / CD profil","csavarok","dübelek","hézagerősítő szalag","glettanyag"]},
"Állványozás":{t:["kalapács","vízmérték","mérőszalag","csavarkulcs","feszítővas","létra"],m:["állványelemek","járólapok / deszkák","rögzítő elemek","korlát / lábdeszka"]},
"Térkövezés":{t:["lapát","talicska","seprű","gumikalapács","vízmérték vagy lézer","vágógép","lapvibrátor"],m:["térkő","ágyazóanyag","homok","szegélykő","beton, ha szükséges"]},
"Aljzatbetonozás":{t:["keverőgép","lapát","talicska","lehúzóléc","vízmérték vagy lézer","simító","vödör"],m:["cement","homok / sóder","víz","dilatációs szalag","fólia, ha szükséges"]},
"Betoncsiszolás":{t:["betoncsiszoló","ipari porszívó","hosszabbító","sarokcsiszoló"],m:["csiszolókorong / gyémántszerszám","javítóanyag, ha szükséges"]},
"Fúrás / vésés":{t:["fúrókalapács","vésőgép","fúrógép","fúrószárak","vésők","ipari porszívó","hosszabbító"],m:["dübelek","csavarok","javítóanyag"]},
"Nyílászáró körüli javítás":{t:["kalapács","véső","sniccer","mérőszalag","vízmérték","fúrógép","csavarozó","spakli","habpisztoly"],m:["purhab","javítóhabarcs","glettanyag","dübel","csavar","szigetelőszalag"]},
"Kőműves javítások":{t:["kalapács","véső","falazókanál","spakli","simító","vízmérték","mérőszalag","keverőgép","vödör"],m:["javítóhabarcs","cement","homok","falazóanyag","glettanyag","víz"]},
"Tereprendezés":{t:["lapát","ásó","gereblye","talicska","döngölő","mérőszalag","lézer / szintező"],m:["töltőanyag","homok","sóder","termőföld","szegélykő, ha szükséges"]},
"Anyagmozgatás":{t:["talicska","molnárkocsi","heveder","gurulós kocsi","lapát","vödör"],m:[]},
"Takarítás / munkaterület-rendezés":{t:["seprű","lapát","ipari porszívó","vödör","felmosó","kézikocsi"],m:["szemeteszsák","tisztítószer","védőfólia"]}
};
const SAFETY=["munkavédelmi bakancs","munkavédelmi kesztyű","védőszemüveg","porálarc / légzésvédelem","hallásvédelem","láthatósági mellény","hosszabbító","elosztó","akkumulátor / töltő","munkalámpa","elsősegélycsomag","ivóvíz","védőfólia / takarás","szemeteszsák"];
const ALWAYS_DEFAULT=["mérőszalag","lézer / szintező","hosszabbító","akkumulátor / töltő","alap kéziszerszámok"];
const KEY="nka_v4",PREVIOUS_KEY="nka_v3",LEGACY_KEY="nka_v2_fixed",YESTERDAY_KEY="nka_v4_yesterday",NOTE_KEY="nka_v4_quick_note",UI_KEY="nka_v4_ui";
const empty=()=>({works:[],status:{},checked:{},ownT:[],ownM:[],ownS:[],notes:{},customWorks:[],always:ALWAYS_DEFAULT.slice(),learning:{}});
const $=selector=>document.querySelector(selector);
const esc=value=>String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[char]));
const itemKey=(kind,name)=>`${kind}::${name}`;
function migrate(){const old=JSON.parse(localStorage.getItem(PREVIOUS_KEY)||localStorage.getItem(LEGACY_KEY)||"null");if(!old)return empty();const next={...empty(),...old};if(old.tools||old.materials){Object.entries(old.tools||{}).filter(([,value])=>value).forEach(([name])=>next.status[itemKey("t",name)]="ready");Object.entries(old.materials||{}).filter(([,value])=>value).forEach(([name])=>next.status[itemKey("m",name)]="ready")};return next}
let state=JSON.parse(localStorage.getItem(KEY)||"null")||migrate();
state={...empty(),...state,status:state.status||{},checked:state.checked||{},notes:state.notes||{},learning:state.learning||{},customWorks:state.customWorks||[],always:state.always||ALWAYS_DEFAULT.slice()};
let mode="",toastTimer;
const ui={workSection:true,toolSection:false,materialSection:false,otherSection:false,alwaysSection:false,learningSection:false,packedSection:false,...JSON.parse(localStorage.getItem(UI_KEY)||"{}")};
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function saveUi(){localStorage.setItem(UI_KEY,JSON.stringify(ui))}
function allWorks(){return {...C,...Object.fromEntries(state.customWorks.map(name=>[name,{t:[],m:[]}]))}}
function unique(values){return [...new Set(values)]}
function listFor(kind){if(kind==="t"||kind==="m")return unique(state.works.flatMap(work=>allWorks()[work]?.[kind]||[]).concat(kind==="t"?state.ownT:state.ownM));if(kind==="s")return unique([...SAFETY,...state.ownS]);return state.always}
function currentStatus(kind,name){return state.status[itemKey(kind,name)]||"pack"}
function setStatus(kind,name,status){state.status[itemKey(kind,name)]=status;save()}
function isChecked(kind,name){return Boolean(state.checked[itemKey(kind,name)])}
function toggleChecked(kind,name){const key=itemKey(kind,name);if(state.checked[key])delete state.checked[key];else state.checked[key]=true;save()}
function toast(message){const el=document.querySelector("#noteStatus");el.textContent=message;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{if(el.textContent===message)el.textContent=""},4000)}
function statusText(status){return({ready:"Megvan",pack:"Pakolni",buy:"Beszerzés"})[status]}
function statusButtons(kind,name){const selected=currentStatus(kind,name);return `<div class="states" aria-label="${esc(name)} állapota">${[["ready","Megvan"],["pack","Pakolni"],["buy","Beszerzés"]].map(([status,label])=>`<button type="button" class="state ${status} ${selected===status?"active":""}" data-status-kind="${kind}" data-status-name="${esc(name)}" data-status="${status}">${label}</button>`).join("")}</div>`}
function bindMics(root=document){root.querySelectorAll("[data-mic-target]").forEach(button=>button.onclick=()=>listen(button.dataset.micTarget))}
function listen(targetId){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){toast("A hangbevitel ezen a böngészőn nem támogatott.");return}const target=document.getElementById(targetId);if(!target)return;const recognition=new Recognition();recognition.lang="hu-HU";recognition.interimResults=false;recognition.maxAlternatives=1;toast("Hallgatlak…");recognition.onresult=event=>{target.value=event.results[0][0].transcript;target.dispatchEvent(new Event("input",{bubbles:true}));target.dispatchEvent(new Event("change",{bubbles:true}));toast("A bemondott szöveg bekerült.")};recognition.onerror=()=>toast("A hangbevitel most nem sikerült.");recognition.start()}
function bindAccordion(){document.querySelectorAll("[data-toggle]").forEach(button=>button.onclick=()=>{const id=button.dataset.toggle;ui[id]=!ui[id];saveUi();render()})}
function drawWorkPicker(){const filter=$("#workSearch").value.trim().toLocaleLowerCase("hu");$("#works").innerHTML=Object.keys(allWorks()).filter(name=>name.toLocaleLowerCase("hu").includes(filter)).map(name=>`<button type="button" class="${state.works.includes(name)?"active":""}" data-work="${esc(name)}">${esc(name)}</button>`).join("")||'<p class="empty">Nincs ilyen munkafolyamat.</p>';$("#works").querySelectorAll("[data-work]").forEach(button=>button.onclick=()=>{const name=button.dataset.work;state.works=state.works.includes(name)?state.works.filter(work=>work!==name):[...state.works,name];save()})}
function drawToday(){const el=$("#selected");$("#workCount").textContent=state.works.length;if(!state.works.length){el.innerHTML='<div class="empty">Még nincs kiválasztott munkafolyamat.</div>';return}el.innerHTML=state.works.map(name=>`<div class="today-work"><strong>${esc(name)}</strong><button type="button" data-remove-work="${esc(name)}" aria-label="${esc(name)} eltávolítása">Eltávolítás ×</button></div>`).join("");el.querySelectorAll("[data-remove-work]").forEach(button=>button.onclick=()=>{state.works=state.works.filter(name=>name!==button.dataset.removeWork);save()})}
function noteId(name,index){return `material-note-${index}-${name.length}`}
function drawList(kind,target,searchId){const own=kind==="t"?state.ownT:kind==="m"?state.ownM:kind==="s"?state.ownS:state.always;const search=$(searchId)?.value.trim().toLocaleLowerCase("hu")||"";const items=listFor(kind).filter(name=>name.toLocaleLowerCase("hu").includes(search));const requiresWork=(kind==="t"||kind==="m")&&!state.works.length;const el=$(target);if(requiresWork){el.innerHTML='<div class="empty">Először válassz legalább egy munkafolyamatot.</div>';return}if(!items.length){el.innerHTML='<div class="empty">Nincs találat.</div>';return}el.innerHTML=items.map((name,index)=>{const isOwn=own.includes(name);const checked=isChecked(kind,name);const id=noteId(name,index);const note=kind==="m"?`<div class="note-row"><input id="${id}" class="note" data-note="${esc(name)}" type="text" placeholder="Mennyiség / megjegyzés" value="${esc(state.notes[name]||"")}"><button type="button" class="mic" data-mic-target="${id}" aria-label="${esc(name)} megjegyzésének bemondása">🎙️</button></div>`:"";return `<article class="item ${currentStatus(kind,name)} ${checked?"is-checked":""}" data-check-row data-check-kind="${kind}" data-check-name="${esc(name)}"><div class="item-top"><input type="checkbox" class="check-item" data-check-kind="${kind}" data-check-name="${esc(name)}" ${checked?"checked":""} aria-label="${esc(name)} ellenőrizve"><div class="itemmain"><strong>${esc(name)}</strong><span>${checked?"Ellenőrizve":""}${checked&&isOwn?" · ":""}${isOwn?"Saját tétel":checked?"":"Szakmai alapjavaslat"}</span></div>${isOwn?`<button type="button" class="remove-item" data-remove-kind="${kind}" data-remove-name="${esc(name)}" aria-label="${esc(name)} törlése">×</button>`:""}</div>${note}${statusButtons(kind,name)}</article>`}).join("");el.querySelectorAll("[data-check-row]").forEach(row=>row.onclick=event=>{if(event.target.closest("button,input"))return;toggleChecked(row.dataset.checkKind,row.dataset.checkName)});el.querySelectorAll(".check-item").forEach(input=>input.onchange=()=>toggleChecked(input.dataset.checkKind,input.dataset.checkName));el.querySelectorAll("[data-status]").forEach(button=>button.onclick=()=>setStatus(button.dataset.statusKind,button.dataset.statusName,button.dataset.status));el.querySelectorAll("[data-note]").forEach(input=>input.onchange=()=>{state.notes[input.dataset.note]=input.value.trim();save()});el.querySelectorAll("[data-remove-kind]").forEach(button=>button.onclick=()=>removeOwn(button.dataset.removeKind,button.dataset.removeName));bindMics(el)}
function removeOwn(kind,name){const property={t:"ownT",m:"ownM",s:"ownS",a:"always"}[kind];state[property]=state[property].filter(item=>item!==name);delete state.status[itemKey(kind,name)];delete state.checked[itemKey(kind,name)];delete state.notes[name];save()}
function learningSuggestions(){const suggestions=[];state.works.forEach(work=>["t","m"].forEach(kind=>Object.entries(state.learning[work]?.[kind]||{}).filter(([,count])=>count>=2).forEach(([name,count])=>suggestions.push({work,kind,name,count}))));return suggestions}
function drawLearning(){const suggestions=learningSuggestions(),el=$("#learning"),section=$("#learningSection");$("#learningCount").textContent=suggestions.length;section.hidden=!suggestions.length;if(!suggestions.length){el.innerHTML="";return}el.innerHTML=suggestions.map(item=>`<div class="suggestion"><span><b>${esc(item.name)}</b><small>${esc(item.work)} · ${item.count} alkalom</small></span><button type="button" data-suggestion-kind="${item.kind}" data-suggestion-name="${esc(item.name)}">Hozzáadás</button></div>`).join("");el.querySelectorAll("[data-suggestion-name]").forEach(button=>button.onclick=()=>{const property=button.dataset.suggestionKind==="t"?"ownT":"ownM";if(!state[property].includes(button.dataset.suggestionName))state[property].push(button.dataset.suggestionName);state.status[itemKey(button.dataset.suggestionKind,button.dataset.suggestionName)]="pack";save()})}
function checklistItems(){return [["t",listFor("t")],["m",listFor("m")],["s",listFor("s")],["a",listFor("a")]].flatMap(([kind,items])=>items.map(name=>({kind,name})))}
function drawPacked(){const items=checklistItems().filter(item=>isChecked(item.kind,item.name)),el=$("#packed"),labels={t:"Szerszámok és gépek",m:"Anyagok",s:"Egyéb kellékek",a:"Mindig ellenőrizd"};$("#packedCount").textContent=items.length;if(!items.length){el.innerHTML='<p class="packed-empty">Még nincs bepipált tétel ezen az eszközön. Jelöld be, amit már bepakoltál.</p>';return}el.innerHTML=items.map(item=>`<article class="packed-item"><span class="packed-tick" aria-hidden="true">✓</span><span><strong>${esc(item.name)}</strong><small>${labels[item.kind]}</small></span><button type="button" data-unpack-kind="${item.kind}" data-unpack-name="${esc(item.name)}">Pipa visszavonása</button></article>`).join("");el.querySelectorAll("[data-unpack-name]").forEach(button=>button.onclick=()=>toggleChecked(button.dataset.unpackKind,button.dataset.unpackName))}
function updateCounts(){[["toolCount","t"],["materialCount","m"],["safetyCount","s"],["alwaysCount","a"]].forEach(([id,kind])=>$("#"+id).textContent=listFor(kind).length);const counts={ready:0,pack:0,buy:0,checked:0,total:0};checklistItems().forEach(({kind,name})=>{counts[currentStatus(kind,name)]++;counts.total++;if(isChecked(kind,name))counts.checked++});$("#ready").textContent=counts.ready;$("#pack").textContent=counts.pack;$("#buy").textContent=counts.buy;$("#checked").textContent=counts.checked;$("#total").textContent=counts.total}
function updateAccordions(){document.querySelectorAll(".accordion").forEach(section=>{const open=Boolean(ui[section.id]);section.classList.toggle("closed",!open);const button=section.querySelector(".accordion-toggle"),panel=section.querySelector(".accordion-panel");button.setAttribute("aria-expanded",String(open));panel.hidden=!open})}
function render(){drawWorkPicker();drawToday();drawList("t","#tools","#toolSearch");drawList("m","#materials","#materialSearch");drawList("s","#safety","#safetySearch");drawList("a","#always",null);drawLearning();drawPacked();updateCounts();updateAccordions();bindAccordion();bindMics()}
function openDialog(kind){mode=kind;const labels={t:"Saját szerszám vagy gép",m:"Saját anyag",s:"Saját helyszíni kellék",a:"Állandó saját felszerelés"};$("#dlgTitle").textContent=labels[kind];$("#dlgText").textContent=kind==="a"?"Ez minden új napi listában megjelenik.":"Adj hozzá egy tételt, amely az alaplistában nem szerepel.";$("#dlgInput").value="";$("#dlg").showModal();$("#dlgInput").focus()}
function snapshot(){return JSON.parse(JSON.stringify(state))}
function captureLearning(day){if(!day.works.length)return;day.works.forEach(work=>{day.learning[work]||={t:{},m:{}};[["t",day.ownT],["m",day.ownM]].forEach(([kind,items])=>items.forEach(name=>{if((day.status[itemKey(kind,name)]||"pack")!=="buy")day.learning[work][kind][name]=(day.learning[work][kind][name]||0)+1}))})}
function dailyText(){const rows=[];[["Szerszámok és gépek","t"],["Anyagok","m"],["Egyéb / helyszíni kellékek","s"]].forEach(([label,kind])=>{const items=listFor(kind);if(!items.length)return;rows.push(`\n${label}:`);items.forEach(name=>rows.push(`• ${name}${kind==="m"&&state.notes[name]?` – ${state.notes[name]}`:""} (${statusText(currentStatus(kind,name))})`))});return `Napi Kivitelezési Asszisztens\nMai munkák: ${state.works.join(", ")||"nincs kiválasztva"}\n${rows.join("\n")}`}
function addWork(){const name=$("#newWork").value.trim();if(!name)return;if(!allWorks()[name])state.customWorks.push(name);if(!state.works.includes(name))state.works.push(name);$("#newWork").value="";save()}
$("#workSearch").oninput=render;$("#toolSearch").oninput=render;$("#materialSearch").oninput=render;$("#safetySearch").oninput=render;$("#addWork").onclick=addWork;$("#newWork").onkeydown=event=>{if(event.key==="Enter")addWork()};
$("#addTool").onclick=()=>openDialog("t");$("#addMaterial").onclick=()=>openDialog("m");$("#addSafety").onclick=()=>openDialog("s");$("#addAlways").onclick=()=>openDialog("a");$("#cancel").onclick=()=>$("#dlg").close();
$("#form").onsubmit=event=>{event.preventDefault();const name=$("#dlgInput").value.trim();if(!name)return;const property={t:"ownT",m:"ownM",s:"ownS",a:"always"}[mode];if(!state[property].includes(name))state[property].push(name);state.status[itemKey(mode,name)]="pack";$("#dlg").close();save()};
$("#quickNote").value=localStorage.getItem(NOTE_KEY)||"";$("#saveQuickNote").onclick=()=>{localStorage.setItem(NOTE_KEY,$("#quickNote").value.trim());toast("A gyorsjegyzet elmentve.")};
$("#reset").onclick=()=>{if(!confirm("A mai lista elmentődik tegnapi listaként. Új napot kezdesz?"))return;const previous=snapshot();captureLearning(previous);localStorage.setItem(YESTERDAY_KEY,JSON.stringify(previous));state=empty();state.always=previous.always||ALWAYS_DEFAULT.slice();state.customWorks=previous.customWorks||[];state.learning=previous.learning||{};save();toast("Új napi lista indult.")};
$("#loadYesterday").onclick=()=>{const previous=JSON.parse(localStorage.getItem(YESTERDAY_KEY)||"null");if(!previous){toast("Még nincs elmentett tegnapi lista.");return}if(!confirm("Betöltöd a legutóbbi napi listát?"))return;state={...empty(),...previous};save()};
$("#print").onclick=()=>window.print();$("#share").onclick=async()=>{try{if(navigator.share)await navigator.share({title:"Napi Kivitelezési Asszisztens",text:dailyText()});else{await navigator.clipboard.writeText(dailyText());toast("A napi lista a vágólapra került.")}}catch(error){if(error.name!=="AbortError")toast("A megosztás most nem sikerült.")}};
render();
